### ISSUE TITLE
Ability to post a new question

### ISSUE THREAD

**Issue by MatJackson** [MatJackson/SD2#11]
SP [ 5 ]
RISK [ HIGH ]
PRIORITY [ HIGH ]

User Story:
A logged in user should be able to create a post using the button on the home page, edit it on the post page, and delete it also on the post page. A user who is not logged in should not be able to do anything other than viewing posts on the post pages.

Front-end task:
- [x] Ability to post question
- [ ] Ability to change font weight, size, italic
- [x] Display user and time stamp
- [x] Ability to edit

Database tasks: 
- [x] Set up new collection for post
- [x] Create schema for post
- [x] Add post to database when it is created
- [x] Update database when post is edited

**Comment by MatJackson** [comment]
For whoever is setting up the backend [here's the mongoose guide (http://mongoosejs.com/docs/guide.html) on how to use schema's and stuff.

note in the example they demonstrate how to make one for a blog, the Question should look fairly similar

```
  var mongoose = require('mongoose');
  var Schema = mongoose.Schema;

  var blogSchema = new Schema({
    title:  String,
    author: String,
    body:   String,
    comments: [{ body: String, date: Date }],
    date: { type: Date, default: Date.now },
    hidden: Boolean,
    meta: {
      votes: Number,
      favs:  Number
    }
  });
```

**Comment by Zhen-Yee** [comment]
Front-end task: 
- [ ] Ability to post question
- [ ] Ability to change font weight, size, italic
- [ ] Display user and time stamp
- [ ] Ability to edit

**Comment by Zhen-Yee** [comment]
Acceptance Test for posting questions: 
- Click on "Quick Post" button on the home page
- Enter "Hi" in the title text box
- Enter "Bye" in the description text box
- Click "Submit" button
- Redirects to post page with title "Hi" and description "Bye"
