### ISSUE TITLE
Fully functional Registration and Login

### ISSUE THREAD

**Issue by MatJackson** [MatJackson/SD2#20]
SP [ 5 ]
RISK [ HIGH ]
PRIORITY [ HIGH ]

User Story:
As a user I shall be able to access the login from the top navigation bar of the site, if I do not have an account the login page will provide a link to the page where I can register for one by entering my e-mail and selecting a username and password.

Task Breakdown:
- [x] Login page layout/design
- [x] Registration page layout/design
- [x] User schema and model for Moongose
- [x] Form validation
- [x] Setup Passport
- [x] user creation and storing in db
- [x] Authentication
- [x] Active Sessions

**Comment by MatJackson** [comment]
Stumbled on [this](https://github.com/braitsch/node-login), could prove useful.

**Comment by MatJackson** [comment]
so I setup a Login/Registration branch that we'll work off of, so any task you work on branch from there. when the whole system is setup we'll pull it to the master. I'm gonna work on setting up passport in such a way that once you guys have the forms set up I'd only need to plug in the id's.

**Comment by StephiieC** [comment]
- [ ] fix error login, page shouldn't be redirected, modal kept open and shows the error
