### ISSUE TITLE
Voting System (Like and Dislike a Question/Answer)

### ISSUE THREAD

**Issue by StephiieC** [MatJackson/SD2#22]
#use bootstrap icon

**Comment by nattganesh** [comment]
1. The system shall allow users to vote whether they like(Up Vote) or dislike(Down Vote) a question. A user shall at a maximum, vote once, either like or dislike, and be able to undo this like or dislike.
2. The system shall allow a similar voting function for the answers to questions.

Task Breakdown:

- [ ]  Create 2 buttons, one for like, and the other for dislike. (Front End)

- [ ] Modify current Schema to include Number Vars for like and dislike, as well as Boolean Vars for whether a user clicked the like or dislike button. (This is to prevent a user from voting more than once on a question / answer)

- [ ] Modify current .ejs files to include Javascript for the functionallity and communication of like and dislike buttons

- [ ] Create two Get methods in app.js, one for like, and the other for dislike

**Comment by nattganesh** [comment]
Will be using Semantic UI for the Like and Dislike Buttons and Icons. 
For more info: https://semantic-ui.com/

**Comment by nattganesh** [comment]
This issue is continued in issue #35
