### ISSUE TITLE
Ability to reply question

### ISSUE THREAD

**Issue by StephiieC** [MatJackson/SD2#24]
SP [4]
RISK [5]
PRIORITY[5]

User Story:
As a user I shall be able to leave comments on a post page once I am logged in using the submit button from the comment section. A user who is not logged in should not be able to do anything other than viewing comments on the post pages.

Front-end tasks:

- [x] Ability to add comment
- [x] Display user and time stamp
- [ ] Ability to edit/delete comment
- [ ] Ability to reply to comments

Database tasks:

- [x] Set up new collection for comments
- [x] Create schema for comments
- [x] Store comments in database
- [ ] Update database when comment is edited/deleted

**Comment by Tomminator97** [comment]
-  Ability to reply to a comment
-  Ability to edit / delete comment
Deferred to Sprint 3, Tracked in #31

**Comment by Tomminator97** [comment]
Closing Issue, further enhancement tracked in #31

**Comment by Tomminator97** [comment]
Acceptance test:
1. Clicked on a post
2. Redirected to post page
3. Typed "testing" in the text area under "Add New Comment To _test_ "
4. Clicked on Submit button
5. Redirected to/Refreshed post page
6. Comment "testing" added under question with time stamp, username
