### ISSUE TITLE
Set Up TravisCI

### ISSUE THREAD

**Issue by MatJackson** [MatJackson/SD2#25]
See end of week 3 DevOps slides

- [ ] Fork [this](https://github.com/swy351/TravisExercise) repository
- [ ]  Read about how to set up Travis CI for your fork here: 
* https://travis-ci.org/
* http://docs.travis-ci.com/user/getting-started/
* http://docs.travis-ci.com/user/languages/java/
* http://docs.travis-ci.com/user/languages/java/#Projects-Using-Ant
* http://docs.travis-ci.com/user/customizing-the-build/

- [ ] Add a .travis.yml file to your forked repository
- [ ] Push a build break into your fork to see if Travis finds it
- [ ] BONUS: Make your repository based on Maven and use Travis to build and test

**Comment by TMERDKH** [comment]
Pull request #26
