### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by MatJackson** [MatJackson/SD2#47]
**SP [3]**
**RISK [ LOW ]**
**PRIORITY [ LOW ]**

User Story:
As a user, if I forget my password I shall be able to click a button on the login page, where I'll be prompted for my username and email, and be allowed to create a new password.

Acceptance tests:
- [x] Ability to click on forget password
- [x] Ability to change password
- [x] User login with new password

**Comment by StephiieC** [comment]
it messes up the login modal when you click:
login > forgot password > login; at this point when you click login, the forgot password part should be gone, this needs to be fixed.

**Comment by nattganesh** [comment]
All Done
