### ISSUE TITLE
Error message for existing username

### ISSUE THREAD

**Issue by Tomminator97** [MatJackson/SD2#60]
SP[1]
PRIORITY[MEDIUM]
Risk[LOW]

As an user, I shall know whether my username is valid during registration. If the chosen username already exists, an error message shall be displayed.

Acceptance test: 
- [ ] error message displayed during registration if username is not unique

**Comment by StephiieC** [comment]
frontend maybe? https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_form_horizontal_all&stacked=h

**Comment by Tomminator97** [comment]
Assigned Andrew to this task because #48  covers this issue
