### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by StephiieC** [MatJackson/SD2#81]
SP [ 5]
RISK [ LOW ]
PRIORITY [ high ]

Sprint 3 we didnt create coding style...

**Comment by JeffreyLi16** [comment]
Coding style for JavaScript is already done in issue #78 .

**Comment by MatJackson** [comment]
This issue needs to be properly formatted as a user story

**Comment by MatJackson** [comment]
coding style guides can be found in the repository readme
